export const UPDATE_TWEET = 'UPDATE_TWEET';
export const TOGGLE_TWEET_BOX_VISIBILITY='TOGGLE_TWEET_BOX_VISIBILITY';
export const TOGGLE_MODAL_VISIBILITY = 'TOGGLE_MODAL_VISIBILITY';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = ' DELETE_POST';
